minimum_pre_commit_version: 1.15.0

ci:
    autofix_prs: false
    autoupdate_schedule: monthly

exclude: "^(\
paper/.*.py\
)"

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: no-commit-to-branch
    - id: check-shebang-scripts-are-executable
    - id: check-executables-have-shebangs
    - id: check-yaml
    - id: check-toml

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black

-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.13.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==23.1.0]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.260
  hooks:
  - id: ruff
    args: [--fix]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: rst-backticks
