# Config file for automatic testing at travis-ci.org

sudo: true
dist: xenial
cache:
  pip: true
  directories:
    - $HOME/.pyenv_cache
    - $HOME/.pyenv

matrix:
  include:
    - os: osx
      language: generic
    - os: linux
      language: python

before_install:
  - export PYTHON_BUILD_CACHE_PATH="$HOME/.pyenv_cache"
  - rm -rf /opt/pyenv
  - |
      if [ ! -d $HOME/.pyenv/.git ]; then
        git clone https://github.com/pyenv/pyenv.git $HOME/.pyenv
      else
        pushd $HOME/.pyenv
        git pull https://github.com/pyenv/pyenv.git
        popd
      fi
  - export PYENV_ROOT="$HOME/.pyenv"
  - export PATH="$HOME/.pyenv/bin:$PATH"
  - eval "$(pyenv init -)"
  - pyenv install -s 3.5.7
  - pyenv install -s 3.6.9
  - pyenv install -s 3.7.5
  - pyenv install -s 3.8.0
  - pyenv local 3.5.7 3.6.9 3.7.5 3.8.0
  - pip install "coverage<5.0"
  - pip install tox tox-pyenv codecov twine

# Command to run tests, e.g. python setup.py test
script: tox -vvv

after_success: codecov
