# Config file for automatic testing at travis-ci.org

language: python
sudo: false
cache:
  pip: true

python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

matrix:
  include:
    - os: osx
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python@2.7 ; fi

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox -vvv

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: nathan.goldbaum
  password:
      secure: "RSHwJlP4iBRcMyVAU8ndpCLler5/Aks1XmtrrOExIE9sJAWGTCUL4mUswRgh/XMTQowrwB8RBed/AJRTRd+pO629os4JntGZ9nFp7stzW93E5oW5Aeca6Q6hRbWQ0wwh1J6rg3t7IjY/4Hd1rVGYVO2KwFn7H1tcRoSsMNjCZ3/HCrXlKhQiOsD4+D1j16KGA9biyABDoNfKxCi45+mQH5wX0qdkVl9KgEB9Bb6EdhflgaWd6XbhuN+UK7zNbH42YyRfUTGgFnmaf574m6SBeI0l30UedA66J9iPwsA6IOUCGwUVSwS8zc3lqwsaqcJQSRwHd0Ey8BhPsE69HjVLfh1tQj+OU8RYNSSgcauZd0+HR0XteEGisXxgKN9sNgFnegyLu0XVjs6vabcqloXAR7R+gSP0k1VZEmE+PFqLEf1CbtjXxDH/bVkmXguf9BGFC30ipP93268cnB/6nnu6bl/5hEoRbaJFjRh6bJGU8BeqFVMk61tHzOGjxGNiJikVV8RUXbRi+iM+WNDyMWfHbQdw46b/nsSLkTXnVuc8uhUo+3eRtcRlZJRcYgTsRJGN/htGs2Zg5z9LAGlzbaQoKuVuFMCAv7pGUkNG9Q/gMkVbCP2uY0/vx4m+Wwfpr2QoGkHHiqxAiQcNsqx7278WmhIx/j4Dvhq2Um+362XFaJw="
  on:
    tags: true
    repo: yt-project/unyt
    python: 3.6
