build: false  # Not a C# project
environment:
  matrix:
    - TOXENV: py27
    - TOXENV: py36

matrix:
  fast_finish: true

install:
  - C:\Python36\python -m pip install --pre -U tox

test_script:
  - C:\Python36\scripts\tox -vvv

cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '%USERPROFILE%\.cache\pre-commit'
