build: false  # Not a C# project
environment:
  matrix:
    - TOXENV: py37

matrix:
  fast_finish: true

install:
  - C:\Python37\python -m pip install --pre -U tox

test_script:
  - C:\Python37\scripts\tox -vvv

cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '%USERPROFILE%\.cache\pre-commit'
